name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag marketcrawler:latest
    - name: Show the Image
    - run: docker images
